### ISSUE TITLE
suport or markdown and asciidoc common extensions.

### ISSUE THREAD

**Issue by teyssieuman** [goeb/reqflow#10]
The '.md' and '.adoc' file support can be easily supported.

**Comment by goeb** [comment]
Sure. '.adoc' is already a know extension in the master branch. I will add '.md' ad well.

**Comment by goeb** [comment]
I added .md and made a release v1.5.3.

**Comment by teyssieuman** [comment]
Thanks for the relativity as well. You were faster to implement than me to check my emails.
