### ISSUE TITLE
Some options are missing

### ISSUE THREAD

**Issue by teyssieuman** [goeb/reqflow#11]
https://github.com/goeb/reqflow/blob/b196915db540a1f1996cb69f1409b55e210b23c7/src/main.cpp#L240

The following options seem to be missing:
* -end-req
* -end-req-style 
* -sort

**Comment by teyssieuman** [comment]
+ -prefix-req

**Comment by goeb** [comment]
Indeed, the comment is not up-to-date.
Thanks for the report.
