### ISSUE TITLE
XLSX parsing

### ISSUE THREAD

**Issue by rolland-esol** [goeb/reqflow#21]
I'd like to parse requirement lists in Excel format.
In my case, the contents are in relatively simple list of columns ID/reqname/reqdescription.
But, XLSX is used instead of CSV because of the possibility to do filtering.
How to get this done?

**Comment by roldud** [comment]
After looking further into adding such parsing, I agree that this is both non-trivial (because a XLSX is a multi-dimensional document, with strings on the side), and that a CSV could be used as an export for a more classic textual input.
Basically, it's just a bad idea...
