### ISSUE TITLE
-end-req and -end-req-style not implemented

### ISSUE THREAD

**Issue by 3adev** [goeb/reqflow#6]
Clauses `-end-req` and `-end-req-style` are not implemented.

I am willing to code an implementation and provide a pull request, except I am not entirely sure what `-end-req-style` is supposed to mean with respect to `-end-req`. Any indications?

Note: I assume `-end-req SOME_REGEX` means "stop capturing requirement when REGEX is met", but if there are some subtle additional semantics to be aware of, please indicate them.

**Comment by goeb** [comment]
Indeed they are not implemented, and your assumption is correct.

At the moment, the text of a requirement is detected (rather roughly) as follows:
- it starts after the requirement identifier
- it ends when the next requirement is encountered (or at the end of the document)

As a reminder, the texts of the requirements are printed by the command "reqflow review".

Feel free to propose an implementation that suits your need.

**Comment by 3adev** [comment]
Thanks for the confirmation.

I have started an implementation and have checked that it now ends the current requirement, not only at the next requirement or at end of file, but also when the regex specified by `-end-req` is met.

This leaves the question of `-end-req-style SOME_REGEX`. What is it supposed to mean?

**Comment by goeb** [comment]
I am not sure about the original idea of the `-end-req-style`. Possibly detect the end of a requirement on a given style (HTML and docx only). But with hindsight, it looks a little awkward.

If you do not have any need about this at the moment, it would be simpler to leave it unchanged and maybe I will simply remove it.

**Comment by 3adev** [comment]
Created PR https://github.com/goeb/reqflow/pull/7

**Comment by goeb** [comment]
Pull request merged.
I close the issue.
