### ISSUE TITLE
HTML report is not showing local time

### ISSUE THREAD

**Issue by damorinCan** [goeb/reqflow#8]
Generating an HTML report is showing at the end, the GMT time.

Example: reqlflow run at 15:56 Montreal time (GMT -5).

Date: 2017-10-18 20:56:38

**Comment by goeb** [comment]
Reqflow's HTML report shows the local time as reported by the OS (C function `localtime()`). Are you sure your OS is reporting a correct local time ?

If I do the test (my localtime is CEST, ie: GMT+2):
- Local time reported by my system: 19 Oct 11:21:22 CEST 2017
- Date of my system in UTC (ie: GMT) : 19 Oct 09:21:22 UTC 2017
- Date in the HTML report: 2017-10-19 11:21:22

Therefore, the date shown in the HTML report is in local time.
I see no issue so far. Could you elaborate?

**Comment by damorinCan** [comment]
Sorry for missing the details.

I'm running reqflow in Win7 and is called inside Cygwin/bash like this:

Got something, when called inside Cygwin/bash, the time is GMT but when called from CMD, it's showing the correct time. Someone had the same issue on StackOverflow:

https://stackoverflow.com/questions/11655003/localtime-returns-gmt-for-windows-programs-running-on-cygwin-shells

**Comment by goeb** [comment]
Do you use the win32 release (https://github.com/goeb/reqflow/releases/download/v1.5.1/reqflow-1.5.1-setup.exe), or did you build yourself reqflow in cygwin?

**Comment by damorinCan** [comment]
I used the Win32 release from github.

I also unset TZ (in Cygwin/bash) and now the date is correct.

**Comment by goeb** [comment]
Ok. I think we can consider this issue as a cygwin environment issue, not a reqflow issue.
I close the issue.
